/*
 * TelaBotao.java
 *
 * Created on 6 de Agosto de 2008, 21:06
 */

package Telas.Formulario;

import Classes.botao;
import Classes.mensagens;
import Controller.ControllerBotao;
import Telas.Tabelas.JTableBotao;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author  Jonathan
 */
public class TelaBotao extends TelaAncestral implements InterfacePadraoTela{
    
    private ControllerBotao Controller;
    private ArrayList<botao> ListaBotao;

    /** Creates new form BeanForm */
    public TelaBotao() {
        initComponents();   
    }

    @Override
    public void IniciarTela() {
        Controller = new ControllerBotao();
        setPanelTela(this.jpnPesquisa, this.jpnCadastro, this.jpnTela);
        super.setTitulo("Botão");
        super.setComportamentoPanel(0);
        super.setComportamentoPanel(1);     
    }    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnTela = new javax.swing.JPanel();
        jpnCadastro = new javax.swing.JPanel();
        jtfTitulo = new javax.swing.JTextField();
        jlb1Titulo = new javax.swing.JLabel();
        jlb1Nome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jlbDescricao = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaDescricao = new javax.swing.JTextArea();
        jpnPesquisa = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbBotao = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jlbDescricao5 = new javax.swing.JLabel();
        jtfNomePesq = new javax.swing.JTextField();
        jlbDescricao4 = new javax.swing.JLabel();
        jtftituloPesq = new javax.swing.JTextField();

        jpnTela.setLayout(new java.awt.BorderLayout());

        jpnCadastro.setBackground(new java.awt.Color(243, 243, 243));

        jtfTitulo.setName("jtfTitulo"); // NOI18N

        jlb1Titulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlb1Titulo.setText("* Titulo");
        jlb1Titulo.setName("jlb1Titulo"); // NOI18N

        jlb1Nome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlb1Nome.setText("* Nome");
        jlb1Nome.setName("jlb1Nome"); // NOI18N

        jtfNome.setName("jtfNome"); // NOI18N

        jlbDescricao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbDescricao.setText("Descrição");
        jlbDescricao.setName("jlbDescricao"); // NOI18N

        jtaDescricao.setColumns(20);
        jtaDescricao.setRows(5);
        jtaDescricao.setName("jtaDescricao"); // NOI18N
        jScrollPane2.setViewportView(jtaDescricao);

        javax.swing.GroupLayout jpnCadastroLayout = new javax.swing.GroupLayout(jpnCadastro);
        jpnCadastro.setLayout(jpnCadastroLayout);
        jpnCadastroLayout.setHorizontalGroup(
            jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCadastroLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpnCadastroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlb1Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnCadastroLayout.createSequentialGroup()
                        .addGroup(jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlb1Nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE))))
                .addGap(61, 61, 61))
        );
        jpnCadastroLayout.setVerticalGroup(
            jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCadastroLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb1Titulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb1Nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbDescricao))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jpnTela.add(jpnCadastro, java.awt.BorderLayout.CENTER);

        jpnPesquisa.setBackground(new java.awt.Color(243, 243, 243));
        jpnPesquisa.setPreferredSize(new java.awt.Dimension(100, 200));
        jpnPesquisa.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jtbBotao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Titulo", "Nome", "Descricao"
            }
        ));
        jtbBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtbBotaoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtbBotao);

        jpnPesquisa.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(243, 243, 243));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 80));

        jlbDescricao5.setText("Nome");

        jlbDescricao4.setText("Titulo");

        jtftituloPesq.setName("jtftituloPesq"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbDescricao4)
                    .addComponent(jlbDescricao5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtftituloPesq, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                    .addComponent(jtfNomePesq, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))
                .addGap(261, 261, 261))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbDescricao4)
                    .addComponent(jtftituloPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbDescricao5)
                    .addComponent(jtfNomePesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jpnPesquisa.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jpnTela.add(jpnPesquisa, java.awt.BorderLayout.PAGE_START);

        getPanelAncestralCriado().add(jpnTela, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void jtbBotaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbBotaoMousePressed
       if ((evt.getClickCount()==1) & (evt.getButton()== MouseEvent.BUTTON1)) {
        if (super.getTipoVisualizacao() == 0) {
            ControllerParaTela(Controller.EventoSelecionar(RetornaId(jtbBotao.getSelectedRow())));
            super.Operacao = 1;
            setComportamento(2);
            setComportamentoPanel(2);
        } else {
            super.jtfRetorno.setText(String.valueOf(RetornaId(jtbBotao.getSelectedRow())));  
            super.FechaFrameInterno();
          }
    }   
}//GEN-LAST:event_jtbBotaoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlb1Nome;
    private javax.swing.JLabel jlb1Titulo;
    private javax.swing.JLabel jlbDescricao;
    private javax.swing.JLabel jlbDescricao4;
    private javax.swing.JLabel jlbDescricao5;
    private javax.swing.JPanel jpnCadastro;
    private javax.swing.JPanel jpnPesquisa;
    private javax.swing.JPanel jpnTela;
    private javax.swing.JTextArea jtaDescricao;
    private javax.swing.JTable jtbBotao;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNomePesq;
    private javax.swing.JTextField jtfTitulo;
    private javax.swing.JTextField jtftituloPesq;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public ArrayList<String> setParametros() {
        ArrayList<String> ListaParametros = new ArrayList<String>();
        if (!(jtftituloPesq.getText().trim().isEmpty())) {
            ListaParametros.add("TituloBotao");
            ListaParametros.add(jtftituloPesq.getText().toString());
        }
        if (!(jtfNomePesq.getText().trim().isEmpty())) {
                ListaParametros.add("NomeBotao");
                ListaParametros.add(jtfNomePesq.getText().toString());
        }           
        return ListaParametros;    
    }

    @Override
    public int RetornaId(int Linha) {
        return ((botao)ListaBotao.get(Linha)).getIdbotao(); 
    }

    @Override
    public void setPanelTela(JPanel jpnPesquisa, JPanel jpnCadastro, JPanel jpnPrincipal) {
        setPanelFilha(jpnPesquisa, jpnCadastro, jpnPrincipal);
    }
    
     @Override
    protected boolean ComportamentoExcluir() {
        if (Controller.EventoExcluir()) {
            JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(5));
            return true;
        } else {
            JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(6));
            return false;
        }
    }

    @Override
    protected boolean ComportamentoSalvar() {
        boolean Gravou = false;
        if (super.VerificaCampos(jpnCadastro, 1)) {
            if (super.Operacao == 0) {                 
                if (Controller.EventoSalvar(TelaParaController())) {
                    JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(2));
                    Gravou = true;
                } else
                    JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(3));
            } else if (super.Operacao == 1) {
                if (Controller.EventoAlterar(TelaParaController())) {
                    JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(4));
                    Gravou = true;
                } else
                    JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(3));                    
                }
            } else JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(1));
        return Gravou;
        }   

    @Override
    protected void ComportamentoNovo() {        
        LimparFormulario(jpnCadastro); 
        super.setComportamentoPanel(2);
    }

    @Override
    protected boolean ComportamentoPesquisar() {
        ArrayList ListaParametros = null;
        boolean Achou = false;
        ListaParametros = setParametros();   
        ListaBotao = Controller.EventoPesquisar(ListaParametros);
        if (ListaBotao.isEmpty()) {
            JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(7));
        } else Achou = true;
        jtbBotao.setModel(new JTableBotao(ListaBotao));       
        return Achou;
    }

    @Override
    public ArrayList<Object> TelaParaController() {
        ArrayList<Object> BotaoLista = new ArrayList<Object>();
        BotaoLista.add(jtfTitulo.getText());
        BotaoLista.add(jtfNome.getText());
        BotaoLista.add(jtaDescricao.getText());
        return BotaoLista;
    }

    @Override
    public void ControllerParaTela(ArrayList<Object> Objeto) {
        jtfTitulo.setText((String)Objeto.get(0));
        jtfNome.setText((String)Objeto.get(1));
        jtaDescricao.setText((String)Objeto.get(2));
    }

    
 

}
