/*
 * TelaSaldoEstoque.java
 *
 * Created on 21 de Agosto de 2008, 21:07
 */

package Telas.Formulario;

import Classes.Funcoes;
import Controller.ControllerSaldoEstoque;
import Telas.Componentes.TelaInterna;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author  Jonathan
 */
public class TelaSaldoEstoque extends javax.swing.JPanel {

    private ControllerSaldoEstoque Controller;
    private int idProduto;
    private Vector ListaSaldo;
    private TelaProduto telaProduto;
    private TelaInterna telaInterna;
    public  JDesktopPane TelaPrincipal;
    /** Creates new form TelaSaldoEstoque */
    public TelaSaldoEstoque() {
        initComponents();
        idProduto = 0;
        Controller = new ControllerSaldoEstoque();
        ListaSaldo = new Vector();
    }
    
    public ArrayList setParametros (){
        ArrayList Lista = new ArrayList();
        Lista.add("produto");
        Lista.add(String.valueOf(idProduto));
        Lista.add("data");
        Lista.add(jftData.getText());
        return Lista;
    }
    
    public void LimparCampos(){
        jtfEntradaAcumulada.setText("");
        jtfSaidaAcumulada.setText("");
        jtfSaldoAtual.setText("");
        jtfSaldoComprometido.setText("");
        jtfSaldoPendente.setText("");
        jtfSaldoComprometidoFuturo.setText("");
        jtfSaldoReal.setText("");     
    }
    
    public boolean ValidaCampos(){
        boolean Preenchido = true;
        if (jtfProduto.getText().equals("")){
            Preenchido = false;
        }
        if (jftData.getText().trim().equals("/  /")){
            Preenchido = false;
        }
        return Preenchido;
    }
    
    private void ControllerParaTela(){
        Vector Lista = ((Vector)ListaSaldo.get(0));
        jtfEntradaAcumulada.setText(Lista.get(0).toString());
        jtfSaidaAcumulada.setText(Lista.get(1).toString());
        jtfSaldoAtual.setText(Lista.get(2).toString());
        jtfSaldoComprometido.setText(Lista.get(3).toString());
        jtfSaldoPendente.setText(Lista.get(4).toString());
        jtfSaldoComprometidoFuturo.setText(Lista.get(5).toString());
        jtfSaldoReal.setText(Lista.get(6).toString());
    }

private void InstaciaTelaProduto(){
    telaProduto = new TelaProduto(); 
    telaProduto.setTipoVisualizacao(1); 
    EscreverMetodosAbstratosTelasInternas();
    CarregarTelaInterna(telaInterna, "Produto", null);        
    CarregarTelaProduto(telaInterna);
        try {
            telaInterna.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
}  

private void EscreverMetodosAbstratosTelasInternas(){
    telaInterna = new TelaInterna(){

        @Override
        public void EventoFechar() {
            //HabilitaForm();               
        }

        @Override
        public void EventoAbrir() {
            //DesabilitaForm();
            //setComponenteTable(false);
        }
    };
}


    
  public void CarregarTelaProduto(TelaInterna Frame){
    telaProduto.setVisible(true);
    //telaPerfil.setJTextRetorno(jtfPerfil);
    telaProduto.setTelaSaldoEstoque(this);
    telaProduto.setFrameInterno(Frame);
    Frame.add(telaProduto);
    TelaPrincipal.add(Frame);
    Frame.setVisible(true);     
} 
  
     protected void CarregarTelaInterna(TelaInterna interna, String titulo, Dimension Tamanho){
        interna.setTitle(titulo);
        interna.setResizable(true);
        interna.setClosable(true);
        interna.setMaximizable(false);
        interna.setIconifiable(false);
        if (Tamanho == null) {
            interna.setSize(700,600);
        } else interna.setSize(Tamanho);
        interna.setLocation(Funcoes.CentralizarFrame(interna.getSize()));
        //return jifTela;
    }
 
public void SetarCamposProduto(Integer Id, String Codigo, String Descricao){
        jtfProduto.setText(Codigo);
        idProduto = Id;    
        edDescProduto.setText(Descricao);
}    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb1Data = new javax.swing.JLabel();
        jlb1Produto = new javax.swing.JLabel();
        jlbEntradaAcumulada = new javax.swing.JLabel();
        jlbSaldoComprometido = new javax.swing.JLabel();
        jlbSaldoPendente = new javax.swing.JLabel();
        jlbSaidaAcumulada = new javax.swing.JLabel();
        jlbSaldoAtual = new javax.swing.JLabel();
        tbAncestral = new javax.swing.JToolBar();
        jbtPesquisar = new javax.swing.JButton();
        jlbTitulo = new javax.swing.JLabel();
        jtfProduto = new javax.swing.JTextField();
        jbtProduto = new javax.swing.JButton();
        jlbSaldoComprometidoFuturo = new javax.swing.JLabel();
        jtfSaldoComprometido = new javax.swing.JTextField();
        jtfSaldoPendente = new javax.swing.JTextField();
        jtfSaldoComprometidoFuturo = new javax.swing.JTextField();
        jtfSaldoAtual = new javax.swing.JTextField();
        jtfSaidaAcumulada = new javax.swing.JTextField();
        jtfEntradaAcumulada = new javax.swing.JTextField();
        jlbSaldoReal = new javax.swing.JLabel();
        jtfSaldoReal = new javax.swing.JTextField();
        MaskFormatter Mask = null;
        try{
            Mask = new MaskFormatter("##/##/####");
        } catch (java.text.ParseException ex){}
        jftData = new javax.swing.JFormattedTextField(Mask);
        edDescProduto = new javax.swing.JTextField();

        setBackground(new java.awt.Color(243, 243, 243));

        jlb1Data.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlb1Data.setText("* Data");
        jlb1Data.setName("jlb1Data"); // NOI18N

        jlb1Produto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlb1Produto.setText("* Produto");
        jlb1Produto.setName("jlb1Produto"); // NOI18N

        jlbEntradaAcumulada.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbEntradaAcumulada.setText("Entrada Acumulada");
        jlbEntradaAcumulada.setName("jlbEntradaAcumulada"); // NOI18N

        jlbSaldoComprometido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbSaldoComprometido.setText("Saldo Comprometido");
        jlbSaldoComprometido.setName("jlbSaldoComprometido"); // NOI18N

        jlbSaldoPendente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbSaldoPendente.setText("Saldo Pendente");
        jlbSaldoPendente.setName("jlbSaldoPendente"); // NOI18N

        jlbSaidaAcumulada.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbSaidaAcumulada.setText("Saida Acumulada");
        jlbSaidaAcumulada.setName("jlbSaidaAcumulada"); // NOI18N

        jlbSaldoAtual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbSaldoAtual.setText("Saldo Atual");
        jlbSaldoAtual.setName("jlbSaldoAtual"); // NOI18N

        tbAncestral.setBackground(new java.awt.Color(243, 243, 243));
        tbAncestral.setFloatable(false);
        tbAncestral.setRollover(true);

        jbtPesquisar.setBackground(new java.awt.Color(243, 243, 243));
        jbtPesquisar.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\Jonathan\\workspace NetBeans\\TCC\\src\\Icones\\Pesquisar.png"));
        jbtPesquisar.setText("Pesquisar"); // NOI18N
        jbtPesquisar.setFocusable(false);
        jbtPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtPesquisar.setName("jbtPesquisar"); // NOI18N
        jbtPesquisar.setPreferredSize(new java.awt.Dimension(53, 40));
        jbtPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtPesquisarMousePressed(evt);
            }
        });
        jbtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPesquisarActionPerformed(evt);
            }
        });
        tbAncestral.add(jbtPesquisar);

        jlbTitulo.setFont(new java.awt.Font("Arial", 1, 14));
        jlbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTitulo.setText("Saldo do Estoque");

        jtfProduto.setName("jtfProduto"); // NOI18N

        jbtProduto.setText("jButton1");
        jbtProduto.setName("jbtProduto"); // NOI18N
        jbtProduto.setPreferredSize(new java.awt.Dimension(4, 19));
        jbtProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtProdutoMousePressed(evt);
            }
        });

        jlbSaldoComprometidoFuturo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbSaldoComprometidoFuturo.setText("Saldo Comprometido Futuro");
        jlbSaldoComprometidoFuturo.setName("jlbSaldoComprometidoFuturo"); // NOI18N

        jtfSaldoComprometido.setBackground(new java.awt.Color(204, 204, 204));
        jtfSaldoComprometido.setEditable(false);
        jtfSaldoComprometido.setFont(new java.awt.Font("Arial", 1, 11));
        jtfSaldoComprometido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfSaldoComprometido.setName("jtfSaldoComprometido"); // NOI18N

        jtfSaldoPendente.setBackground(new java.awt.Color(204, 204, 204));
        jtfSaldoPendente.setEditable(false);
        jtfSaldoPendente.setFont(new java.awt.Font("Arial", 1, 11));
        jtfSaldoPendente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfSaldoPendente.setName("jtfSaldoPendente"); // NOI18N

        jtfSaldoComprometidoFuturo.setBackground(new java.awt.Color(204, 204, 204));
        jtfSaldoComprometidoFuturo.setEditable(false);
        jtfSaldoComprometidoFuturo.setFont(new java.awt.Font("Arial", 1, 11));
        jtfSaldoComprometidoFuturo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfSaldoComprometidoFuturo.setName("jtfSaldoComprometidoFuturo"); // NOI18N

        jtfSaldoAtual.setBackground(new java.awt.Color(204, 204, 204));
        jtfSaldoAtual.setEditable(false);
        jtfSaldoAtual.setFont(new java.awt.Font("Arial", 1, 11));
        jtfSaldoAtual.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfSaldoAtual.setName("jtfSaldoAtual"); // NOI18N

        jtfSaidaAcumulada.setBackground(new java.awt.Color(204, 204, 204));
        jtfSaidaAcumulada.setEditable(false);
        jtfSaidaAcumulada.setFont(new java.awt.Font("Arial", 1, 11));
        jtfSaidaAcumulada.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfSaidaAcumulada.setName("jtfSaidaAcumulada"); // NOI18N

        jtfEntradaAcumulada.setBackground(new java.awt.Color(204, 204, 204));
        jtfEntradaAcumulada.setEditable(false);
        jtfEntradaAcumulada.setFont(new java.awt.Font("Arial", 1, 11));
        jtfEntradaAcumulada.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfEntradaAcumulada.setName("jtfEntradaAcumulada"); // NOI18N

        jlbSaldoReal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbSaldoReal.setText("Saldo Real");
        jlbSaldoReal.setName("jlbSaldoReal"); // NOI18N

        jtfSaldoReal.setBackground(new java.awt.Color(204, 204, 204));
        jtfSaldoReal.setEditable(false);
        jtfSaldoReal.setFont(new java.awt.Font("Arial", 1, 11));
        jtfSaldoReal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfSaldoReal.setName("jtfSaldoReal"); // NOI18N

        jftData.setName("jftData"); // NOI18N

        edDescProduto.setBackground(new java.awt.Color(204, 204, 204));
        edDescProduto.setEditable(false);
        edDescProduto.setFont(new java.awt.Font("Arial", 1, 11));
        edDescProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        edDescProduto.setName("edDescProduto"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbSaldoAtual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jlbSaidaAcumulada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jlbEntradaAcumulada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jlb1Data, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jlb1Produto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jlbSaldoReal, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jftData, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfEntradaAcumulada, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jtfSaidaAcumulada, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jtfSaldoAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jtfSaldoReal, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbSaldoPendente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbSaldoComprometido, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(jlbSaldoComprometidoFuturo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfSaldoComprometido, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(jtfSaldoPendente, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(jtfSaldoComprometidoFuturo, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))
                    .addComponent(edDescProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jtfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jbtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(363, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbAncestral, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
            .addComponent(jlbTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(tbAncestral, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jtfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlb1Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlb1Data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jftData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(edDescProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jlbEntradaAcumulada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfEntradaAcumulada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbSaldoComprometido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfSaldoComprometido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jlbSaidaAcumulada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfSaidaAcumulada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbSaldoPendente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfSaldoPendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jlbSaldoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfSaldoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbSaldoComprometidoFuturo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfSaldoComprometidoFuturo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jbtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbSaldoReal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfSaldoReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(196, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jbtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPesquisarActionPerformed

}//GEN-LAST:event_jbtPesquisarActionPerformed

private void jbtProdutoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtProdutoMousePressed
    InstaciaTelaProduto();
}//GEN-LAST:event_jbtProdutoMousePressed

private void jbtPesquisarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtPesquisarMousePressed
    if (ValidaCampos()) {
        LimparCampos();
        ListaSaldo = Controller.EventoPesquisar(setParametros());
        ControllerParaTela();
    }
}//GEN-LAST:event_jbtPesquisarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField edDescProduto;
    public javax.swing.JButton jbtPesquisar;
    private javax.swing.JButton jbtProduto;
    private javax.swing.JFormattedTextField jftData;
    private javax.swing.JLabel jlb1Data;
    private javax.swing.JLabel jlb1Produto;
    private javax.swing.JLabel jlbEntradaAcumulada;
    private javax.swing.JLabel jlbSaidaAcumulada;
    private javax.swing.JLabel jlbSaldoAtual;
    private javax.swing.JLabel jlbSaldoComprometido;
    private javax.swing.JLabel jlbSaldoComprometidoFuturo;
    private javax.swing.JLabel jlbSaldoPendente;
    private javax.swing.JLabel jlbSaldoReal;
    private javax.swing.JLabel jlbTitulo;
    private javax.swing.JTextField jtfEntradaAcumulada;
    private javax.swing.JTextField jtfProduto;
    private javax.swing.JTextField jtfSaidaAcumulada;
    private javax.swing.JTextField jtfSaldoAtual;
    private javax.swing.JTextField jtfSaldoComprometido;
    private javax.swing.JTextField jtfSaldoComprometidoFuturo;
    private javax.swing.JTextField jtfSaldoPendente;
    private javax.swing.JTextField jtfSaldoReal;
    private javax.swing.JToolBar tbAncestral;
    // End of variables declaration//GEN-END:variables

}
