/*
 * TelaCadastroTela.java
 *
 * Created on 8 de Agosto de 2008, 09:07
 */

package Telas.Formulario;

import Classes.Funcoes;
import Classes.botao;
import Controller.ControllerTela;
import Telas.Componentes.TelaInterna;
import Telas.Tabelas.JTableTela;
import Telas.Tabelas.JTableTelaBotao;
import java.awt.event.MouseEvent;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Telas.Formulario.TelaPerfil;
        

/**
 *
 * @author  jonathan
 */
public class TelaCadastroTela extends TelaAncestral implements InterfacePadraoAcessoOutrasTelas{
    
    private ControllerTela Controller;
    private ArrayList<Object> ListaTela;
    private ArrayList<Object> ListaTelaTrabalho = new ArrayList<Object>();
    private ArrayList<botao> ListaTelaBotao = new ArrayList<botao>();
    private JDesktopPane TelaPrincipal;
    private botao Botao;
    private TelaBotao telaBotao;
    private TelaPerfil telaPerfil;
    
    /** Creates new form BeanForm */
    public TelaCadastroTela() {
        initComponents();
        IniciarTela();
    }
    
    public TelaCadastroTela(TelaPerfil Perfil) {
        initComponents();
        IniciarTela();
        telaPerfil = Perfil;
    }
    
            
    public void IniciarTela() {
        super.setTitulo("Tela");
        Controller = new ControllerTela();
        funcoes = new Funcoes();
        setPanelTela(this.jpnPesquisa, this.jpnCadastro, this.jpnTela);
        super.setTitulo("Tela");
        super.setComportamentoPanel(0);
        super.setComportamentoPanel(1);      
        CriarListaTelaTrabalho();        
    }
    private void CriarListaTelaTrabalho(){
        ListaTelaTrabalho.add("");
        ListaTelaTrabalho.add("");
        ListaTelaTrabalho.add("");
        ListaTelaTrabalho.add(new ArrayList<Object>());
    }
    
    private void LimparListaTelaTrabalho(){
        ListaTelaTrabalho.set(0,"");
        ListaTelaTrabalho.set(1,"");
        ListaTelaTrabalho.set(2,"");
        ListaTelaTrabalho.set(3, new ArrayList<Object>());        
    }
    
    @Override
    public void setDesktopPane(JDesktopPane Pane){
        TelaPrincipal = Pane;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnTela = new javax.swing.JPanel();
        jpnCadastro = new javax.swing.JPanel();
        jtfTituloTela = new javax.swing.JTextField();
        jtfNomeMenu = new javax.swing.JTextField();
        jlb1NomeTela = new javax.swing.JLabel();
        jlb1TituloTela = new javax.swing.JLabel();
        jlb1NomeMenu = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jlbBot = new javax.swing.JLabel();
        jtfNomeBotao = new javax.swing.JTextField();
        jbtBotaoPesquisa = new javax.swing.JButton();
        jlb2NomeBotao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtbTelaBotao = new javax.swing.JTable();
        jtfAdicionar = new javax.swing.JButton();
        jtfExcluir = new javax.swing.JButton();
        jtfBotaoDescricao = new javax.swing.JTextField();
        jtfNomeTela = new javax.swing.JTextField();
        jpnPesquisa = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jlbNomeTela1 = new javax.swing.JLabel();
        jtfNomeTelaPesq = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfTituloTelaPesq = new javax.swing.JTextField();
        jlbNomeMenu1 = new javax.swing.JLabel();
        jtfNomeMenuPesq = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbTela = new javax.swing.JTable();

        jpnTela.setLayout(new java.awt.BorderLayout());

        jpnCadastro.setBackground(new java.awt.Color(243, 243, 243));
        jpnCadastro.setName("jpnCadastro"); // NOI18N

        jtfTituloTela.setName("jtfTituloTela"); // NOI18N

        jtfNomeMenu.setName("jtfNomeMenu"); // NOI18N

        jlb1NomeTela.setText("* Nome");
        jlb1NomeTela.setName("jlb1NomeTela"); // NOI18N

        jlb1TituloTela.setText("* Titulo");
        jlb1TituloTela.setName("jlb1TituloTela"); // NOI18N

        jlb1NomeMenu.setText("* Nome Menu");
        jlb1NomeMenu.setName("jlb1NomeMenu"); // NOI18N

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 2));

        jlbBot.setText("Botões");
        jlbBot.setName("jlbBot"); // NOI18N

        jtfNomeBotao.setName("jtfNomeBotao"); // NOI18N
        jtfNomeBotao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNomeBotaoFocusLost(evt);
            }
        });

        jbtBotaoPesquisa.setText("jButton1");
        jbtBotaoPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtBotaoPesquisaMousePressed(evt);
            }
        });

        jlb2NomeBotao.setText("* Nome Botão");
        jlb2NomeBotao.setName("jlb2NomeBotao"); // NOI18N

        JtbTelaBotao.setBackground(new java.awt.Color(243, 243, 243));
        JtbTelaBotao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Descrição", "Função"
            }
        ));
        jScrollPane1.setViewportView(JtbTelaBotao);

        jtfAdicionar.setText("Adicionar");
        jtfAdicionar.setName("jtfAdicionar"); // NOI18N
        jtfAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtfAdicionarMousePressed(evt);
            }
        });
        jtfAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAdicionarActionPerformed(evt);
            }
        });

        jtfExcluir.setText("Excluir");
        jtfExcluir.setName("jtfExcluir"); // NOI18N
        jtfExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtfExcluirMousePressed(evt);
            }
        });

        jtfBotaoDescricao.setEditable(false);
        jtfBotaoDescricao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtfBotaoDescricao.setEnabled(false);
        jtfBotaoDescricao.setName("jtfBotao"); // NOI18N
        jtfBotaoDescricao.setSelectionColor(new java.awt.Color(102, 102, 102));
        jtfBotaoDescricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfBotaoDescricaoFocusLost(evt);
            }
        });

        jtfNomeTela.setName("jtfNomeTela"); // NOI18N

        javax.swing.GroupLayout jpnCadastroLayout = new javax.swing.GroupLayout(jpnCadastro);
        jpnCadastro.setLayout(jpnCadastroLayout);
        jpnCadastroLayout.setHorizontalGroup(
            jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCadastroLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlb1NomeTela)
                    .addComponent(jlb1NomeMenu)
                    .addComponent(jlb1TituloTela))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfNomeMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addComponent(jtfTituloTela, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addComponent(jtfNomeTela, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(jpnCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnCadastroLayout.createSequentialGroup()
                        .addComponent(jlbBot)
                        .addContainerGap(502, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCadastroLayout.createSequentialGroup()
                        .addGroup(jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                            .addGroup(jpnCadastroLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jlb2NomeBotao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnCadastroLayout.createSequentialGroup()
                                        .addComponent(jtfNomeBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbtBotaoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jtfBotaoDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(jtfAdicionar))))
                        .addGap(19, 19, 19))))
        );
        jpnCadastroLayout.setVerticalGroup(
            jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb1NomeTela)
                    .addComponent(jtfNomeTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTituloTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb1TituloTela))
                .addGap(6, 6, 6)
                .addGroup(jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb1NomeMenu)
                    .addComponent(jtfNomeMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jlbBot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfNomeBotao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlb2NomeBotao))
                    .addGroup(jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtBotaoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfBotaoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnCadastroLayout.createSequentialGroup()
                        .addComponent(jtfAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfExcluir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(253, 253, 253))
        );

        jpnTela.add(jpnCadastro, java.awt.BorderLayout.CENTER);

        jpnPesquisa.setBackground(new java.awt.Color(243, 243, 243));
        jpnPesquisa.setPreferredSize(new java.awt.Dimension(100, 180));
        jpnPesquisa.setLayout(new java.awt.BorderLayout());

        jlbNomeTela1.setText("Nome");
        jlbNomeTela1.setName("jlbNomeTela"); // NOI18N

        jtfNomeTelaPesq.setName("jtfNomeTela"); // NOI18N

        jLabel3.setText("Titulo");

        jtfTituloTelaPesq.setName("jtfTituloTela"); // NOI18N

        jlbNomeMenu1.setText("Nome Menu");
        jlbNomeMenu1.setName("jlbNomeMenu"); // NOI18N

        jtfNomeMenuPesq.setName("jtfNomeMenu"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlbNomeTela1)
                    .addComponent(jLabel3)
                    .addComponent(jlbNomeMenu1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfNomeMenuPesq, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                    .addComponent(jtfTituloTelaPesq, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                    .addComponent(jtfNomeTelaPesq, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                .addGap(133, 133, 133))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNomeTela1)
                    .addComponent(jtfNomeTelaPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTituloTelaPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNomeMenuPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbNomeMenu1))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jpnPesquisa.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jtbTela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Titulo", "Nome", "Nome Menu"
            }
        ));
        jtbTela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtbTelaMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jtbTela);

        jpnPesquisa.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jpnTela.add(jpnPesquisa, java.awt.BorderLayout.PAGE_START);

        getPanelAncestralCriado().add(jpnTela, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void jtbTelaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbTelaMousePressed
    if ((evt.getClickCount()==1) & (evt.getButton()== MouseEvent.BUTTON1)) {
        if (super.getTipoVisualizacao() == 0) {
            ControllerParaTela(Controller.EventoSelecionar(RetornaId(jtbTela.getSelectedRow())));
            super.Operacao = 1;
            setComportamento(2);
            setComportamentoPanel(2);            
            super.setLocalizacao(1);
            SetArraySelecionar();
            super.setComportamentoPanel(2);
        } else {            
            int IdTela = RetornaId(jtbTela.getSelectedRow());
            telaPerfil.SetarCamposVindoDaTelaCadastroTela(IdTela, (String)((Vector)ListaTela.get(jtbTela.getSelectedRow())).get(2)) ;
            super.FechaFrameInterno();
          }
    }   
}//GEN-LAST:event_jtbTelaMousePressed

@Override
public void SetArraySelecionar(){
    /* ListaTelaBotao.clear();
     for (Iterator<botao> it = Tela.getbotaoCollection().iterator(); it.hasNext();) {
        botao object = it.next();
        ListaTelaBotao.add(object);
     }*/
}

private void jbtBotaoPesquisaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtBotaoPesquisaMousePressed
    telaBotao = new TelaBotao();
    telaBotao.setTipoVisualizacao(1);
    TelaInterna telaInterna = new TelaInterna() {

            @Override
            public void EventoFechar() {
               HabilitaForm(); 
            }

            @Override
            public void EventoAbrir() {
               DesabilitaForm();
            }
        };
    super.CarregarTelaInterna(telaInterna, "Botão", null);
    CarregarTela(telaInterna);
        try {
            telaInterna.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }  
}//GEN-LAST:event_jbtBotaoPesquisaMousePressed

private void jtfAdicionarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfAdicionarMousePressed
    if (super.VerificaCampos(jpnCadastro, 2)) {
        //ListaTelaTrabalho.add(Controller.AdicionarBotao(Integer.parseInt(jtfNomeBotao.getText())));
        ((ArrayList)ListaTelaTrabalho.get(3)).add(Controller.AdicionarBotao(Integer.parseInt(jtfNomeBotao.getText())));        
        //ListaTelaTrabalho.set(3, Controller.AdicionarBotao(Integer.parseInt(jtfNomeBotao.getText())));        
        JtbTelaBotao.setModel(new JTableTelaBotao((ArrayList<Object>)ListaTelaTrabalho.get(3)));
    } else {
        JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(1));
    }
}//GEN-LAST:event_jtfAdicionarMousePressed


private void jtfExcluirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfExcluirMousePressed
   ((ArrayList)ListaTelaTrabalho.get(3)).remove(JtbTelaBotao.getSelectedRow());
   JtbTelaBotao.setModel(new JTableTelaBotao((ArrayList)ListaTelaTrabalho.get(3))); 
}//GEN-LAST:event_jtfExcluirMousePressed

private void jtfNomeBotaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNomeBotaoFocusLost
    jtfBotaoDescricao.setText("");
    if (!(jtfNomeBotao.getText().trim().equals(""))) {        
        jtfBotaoDescricao.setText(((ArrayList)Controller.AdicionarBotao(Integer.parseInt(jtfNomeBotao.getText()))).get(1).toString());
    }
}//GEN-LAST:event_jtfNomeBotaoFocusLost

private void jtfBotaoDescricaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfBotaoDescricaoFocusLost
// TODO add your handling code here:
}//GEN-LAST:event_jtfBotaoDescricaoFocusLost

private void jtfAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAdicionarActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jtfAdicionarActionPerformed
                                      
@Override
public void CarregarTela(TelaInterna Frame){
    telaBotao.setVisible(true);
    telaBotao.setJTextRetorno(jtfNomeBotao);
    telaBotao.setFrameInterno(Frame);
    Frame.add(telaBotao);
    TelaPrincipal.add(Frame);
    Frame.setVisible(true);     
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtbTelaBotao;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtBotaoPesquisa;
    private javax.swing.JLabel jlb1NomeMenu;
    private javax.swing.JLabel jlb1NomeTela;
    private javax.swing.JLabel jlb1TituloTela;
    private javax.swing.JLabel jlb2NomeBotao;
    private javax.swing.JLabel jlbBot;
    private javax.swing.JLabel jlbNomeMenu1;
    private javax.swing.JLabel jlbNomeTela1;
    private javax.swing.JPanel jpnCadastro;
    private javax.swing.JPanel jpnPesquisa;
    private javax.swing.JPanel jpnTela;
    private javax.swing.JTable jtbTela;
    private javax.swing.JButton jtfAdicionar;
    private javax.swing.JTextField jtfBotaoDescricao;
    private javax.swing.JButton jtfExcluir;
    private javax.swing.JTextField jtfNomeBotao;
    private javax.swing.JTextField jtfNomeMenu;
    private javax.swing.JTextField jtfNomeMenuPesq;
    private javax.swing.JTextField jtfNomeTela;
    private javax.swing.JTextField jtfNomeTelaPesq;
    private javax.swing.JTextField jtfTituloTela;
    private javax.swing.JTextField jtfTituloTelaPesq;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setPanelTela(JPanel jpnPesquisa, JPanel jpnCadastro, JPanel jpnPrincipal) {
        setPanelFilha(jpnPesquisa, jpnCadastro, jpnPrincipal);
    }

    @Override
    public ArrayList<String> setParametros() {
        ArrayList<String> ListaParametros = new ArrayList<String>();
        //ListaParametros = null;
        return ListaParametros;
    }

    @Override
    public int RetornaId(int Linha) {
        return Integer.parseInt(((Vector)ListaTela.get(Linha)).get(0).toString()); 
    }

    @Override
    protected boolean ComportamentoSalvar() {
        boolean Gravou = false;
        if (super.VerificaCampos(jpnCadastro, 1)) {
            if (super.Operacao == 0) { 
                if (Controller.EventoSalvar(TelaParaController())) {
                    JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(2));
                    Gravou = true;
                } else
                    JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(3));
            } else if (super.Operacao == 1) {
                if (Controller.EventoAlterar(TelaParaController())) {
                    JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(4));
                    Gravou = true;
                } else
                    JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(3));                    
                }
            } else JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(1));
        return Gravou;
        }  
    
    @Override
    protected boolean ComportamentoExcluir() {
        boolean Excluiu = false;
        if (Controller.EventoExcluir()) {
            JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(5));
            Excluiu = true;
        } else {
            JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(6));
        }
        return Excluiu;
    }
    

    @Override
    protected boolean ComportamentoPesquisar() {
        boolean Achou = false;
        ArrayList ListaParametros = null;
        ListaParametros = setParametros();   
        ListaTela = Controller.EventoPesquisar(ListaParametros);
        if (ListaTela.isEmpty()) {
            JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(7));
        } else Achou = true;
        jtbTela.setModel(new JTableTela(ListaTela));   
        return Achou;
    }    
    
    @Override
    protected void ComportamentoNovo() {  
        LimparFormulario(jpnCadastro); 
        super.setComportamentoPanel(2);   
        ListaTelaTrabalho.set(3, new ArrayList<Object>());        
        JtbTelaBotao.setModel(new JTableTelaBotao(new ArrayList()));
    }

    @Override
    public ArrayList<Object> TelaParaController() {
        ListaTelaTrabalho.set(0, jtfNomeTela.getText());
        ListaTelaTrabalho.set(1, jtfTituloTela.getText());
        ListaTelaTrabalho.set(2, jtfNomeMenu.getText());
        return ListaTelaTrabalho;
    }

    @Override
    public void ControllerParaTela(ArrayList<Object> Objeto) {
        ListaTelaTrabalho.clear();
        ListaTelaTrabalho = Objeto;
        jtfNomeTela.setText((String)Objeto.get(0));
        jtfTituloTela.setText((String)Objeto.get(1));
        jtfNomeMenu.setText((String)Objeto.get(2));
        JtbTelaBotao.setModel(new JTableTelaBotao((ArrayList)Objeto.get(3)));
    }


}
