/*
 * TelaLogin.java
 *
 * Created on 21 de Agosto de 2008, 20:47
 */

package Telas;

import Classes.Funcoes;
import Classes.UsuarioSistema;
import Classes.logsistema;
import Classes.mensagens;
import Classes.usuario;
import Telas.TelaInicioVelho;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author  Jonathan
 */
public class TelaLogin extends javax.swing.JFrame {
    
    private UsuarioSistema usuarioSistema;
    private mensagens Mensagens;
    private logsistema Log;
    private Funcoes funcoes;

    /** Creates new form TelaLogin */
    public TelaLogin() {
        initComponents();
        this.setSize(new Dimension(406, 221));
        this.setLocation(Funcoes.CentralizarFrame(this.getSize()));
        usuarioSistema = new UsuarioSistema();
        Log = new logsistema();
        Mensagens = new mensagens();
        setVisibilidaCompAlterar(false);
        funcoes = new Funcoes();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jlbStatus = new javax.swing.JLabel();
        jpbStatus = new javax.swing.JProgressBar();
        jlbNovaSenha = new javax.swing.JLabel();
        jpfNovaSenha = new javax.swing.JPasswordField();
        jlbBoasVindas = new javax.swing.JLabel();
        jlbSenha = new javax.swing.JLabel();
        jbtAlterar = new javax.swing.JButton();
        jbtEntrar = new javax.swing.JButton();
        jtfLogin = new javax.swing.JTextField();
        jpfSenha = new javax.swing.JPasswordField();
        jlbUsuario = new javax.swing.JLabel();
        jbtDesfazer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(243, 243, 243));
        setExtendedState(1);
        setResizable(false);
        getContentPane().setLayout(null);

        jlbStatus.setName("jlbStatus"); // NOI18N
        jlbStatus.setPreferredSize(new java.awt.Dimension(71, 14));
        getContentPane().add(jlbStatus);
        jlbStatus.setBounds(10, 150, 380, 14);

        jpbStatus.setName("jpbStatus"); // NOI18N
        getContentPane().add(jpbStatus);
        jpbStatus.setBounds(0, 170, 400, 19);

        jlbNovaSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbNovaSenha.setText("* Nova senha");
        getContentPane().add(jlbNovaSenha);
        jlbNovaSenha.setBounds(27, 120, 80, 20);
        getContentPane().add(jpfNovaSenha);
        jpfNovaSenha.setBounds(120, 120, 165, 20);

        jlbBoasVindas.setFont(new java.awt.Font("Arial", 1, 14));
        jlbBoasVindas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbBoasVindas.setText("BEM-VINDO AO SICON");
        getContentPane().add(jlbBoasVindas);
        jlbBoasVindas.setBounds(120, 10, 160, 20);

        jlbSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbSenha.setText("* Senha");
        getContentPane().add(jlbSenha);
        jlbSenha.setBounds(50, 65, 60, 20);

        jbtAlterar.setText("Alterar");
        jbtAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtAlterarMousePressed(evt);
            }
        });
        getContentPane().add(jbtAlterar);
        jbtAlterar.setBounds(210, 90, 77, 23);

        jbtEntrar.setText("Entrar");
        jbtEntrar.setName("jbtEntrar"); // NOI18N
        jbtEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtEntrarMousePressed(evt);
            }
        });
        jbtEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEntrarActionPerformed(evt);
            }
        });
        jbtEntrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtEntrarKeyPressed(evt);
            }
        });
        getContentPane().add(jbtEntrar);
        jbtEntrar.setBounds(120, 90, 77, 23);

        jtfLogin.setText("jrtm");
        jtfLogin.setName("jtfLogin"); // NOI18N
        getContentPane().add(jtfLogin);
        jtfLogin.setBounds(120, 40, 165, 20);

        jpfSenha.setText("sicon");
        jpfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpfSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(jpfSenha);
        jpfSenha.setBounds(120, 65, 165, 20);

        jlbUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbUsuario.setText("* Usuário");
        getContentPane().add(jlbUsuario);
        jlbUsuario.setBounds(30, 40, 80, 20);

        jbtDesfazer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtDesfazer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtDesfazerMousePressed(evt);
            }
        });
        getContentPane().add(jbtDesfazer);
        jbtDesfazer.setBounds(287, 120, 20, 19);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jbtAlterarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtAlterarMousePressed
    if (jbtAlterar.getText().equals("Alterar")) {
        setPosicaoCompAlterar(true);
        jbtAlterar.setText("Salvar");
    } else {
        if (ValidaCampoObrigatorio(true)) {
            CarregarUsuario();
            if (ValidarSenha()) {
                if (!(jpfNovaSenha.getPassword().equals(jpfSenha.getPassword()))) {
                    usuarioSistema.getUsuario().setSenha(Funcoes.CharToString(jpfNovaSenha.getPassword()));
                    if (usuarioSistema.getUsuario().Gravar(1)) {
                        JOptionPane.showMessageDialog(null, Mensagens.RetornaMensagem(4));
                        jpfSenha.setText(usuarioSistema.getUsuario().getSenha());
                    } else JOptionPane.showMessageDialog(null, Mensagens.RetornaMensagem(3));
                } else {
                    JOptionPane.showMessageDialog(null, Mensagens.RetornaMensagem(10));
                } 
            } else JOptionPane.showMessageDialog(null, Mensagens.RetornaMensagem(9));
        }
        setPosicaoCompAlterar(false);
        jbtAlterar.setText("Alterar");        
    }
    
}//GEN-LAST:event_jbtAlterarMousePressed

private void jbtDesfazerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtDesfazerMousePressed
    setPosicaoCompAlterar(false);
    jbtAlterar.setText("Alterar");
}//GEN-LAST:event_jbtDesfazerMousePressed

private void jbtEntrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtEntrarMousePressed
    EntrarNoSistema();
    setLog();
    Log.Gravar();
}//GEN-LAST:event_jbtEntrarMousePressed

private void jbtEntrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtEntrarKeyPressed

}//GEN-LAST:event_jbtEntrarKeyPressed

private void jpfSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfSenhaKeyPressed
  if (evt.getKeyCode() == KeyEvent.VK_ENTER)  {
    EntrarNoSistema();
    setLog();
    Log.Gravar();
  }
}//GEN-LAST:event_jpfSenhaKeyPressed

private void jbtEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEntrarActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jbtEntrarActionPerformed

private void setLog(){
    Log.setUsuario(usuarioSistema.getUsuario());
    GregorianCalendar data = new GregorianCalendar();
    Log.setHorario(new Timestamp(data.getTimeInMillis()));
    Log.setOperacao("Entrada");    
}

private void setPosicaoBotoes(boolean Alterar) {
    if (Alterar) {
        jbtAlterar.setLocation(210, 120);
        jbtEntrar.setLocation(120, 120);
    } else {
        jbtAlterar.setLocation(210, 90);
        jbtEntrar.setLocation(120, 90);        
    }
}
private void setPosicaoCompAlterar(boolean visivel){
    if (visivel) {        
        jpfNovaSenha.setLocation(120, 90);
        jlbNovaSenha.setLocation(27, 90);
        jbtDesfazer.setLocation(287, 90);
        setPosicaoBotoes(visivel);
        setVisibilidaCompAlterar(visivel);         
    } else {
        jpfNovaSenha.setLocation(120, 120);
        jlbNovaSenha.setLocation(27, 120);
        jbtDesfazer.setLocation(287, 120);
        setPosicaoBotoes(visivel);
        setVisibilidaCompAlterar(visivel);      
    }
    setVisibilidaCompAlterar(visivel);
}
private boolean CarregarUsuario(){
   return usuarioSistema.CarregarUsuario(jtfLogin.getText().trim());
}


private void setVisibilidaCompAlterar(boolean visivel){
    jpfNovaSenha.setVisible(visivel);
    jlbNovaSenha.setVisible(visivel);
    jbtDesfazer.setVisible(visivel);    
}

private boolean ValidarSenha(){
    if (usuarioSistema.getUsuario().getSenha().equals(Funcoes.CharToString(jpfSenha.getPassword()))) {
        return true;
    } else {
        return false;
    }   
}


public void setLabelStatus(String Texto){
    jlbStatus.setText(Texto);
    jlbStatus.repaint();
}

public void setProgressao(){
    jpbStatus.setValue(jpbStatus.getValue() + 1);
    //jpbStatus.setPro
}

public void setProgressaoMaximum(int valor) {
    jpbStatus.setMaximum(jpbStatus.getMinimum() + valor);
}
private void EntrarNoSistema(){
    jpbStatus.setMaximum(3);
    jpbStatus.setMinimum(0);    
    jpbStatus.setValue(1);
    setLabelStatus("Verificando campos obrigatórios... ");
    if (ValidaCampoObrigatorio(false)) {
        setLabelStatus("Carregando usuário...");
        if (!(CarregarUsuario())) {
            JOptionPane.showMessageDialog(null, Mensagens.RetornaMensagem(8));
            jtfLogin.requestFocus(true);
            jpbStatus.setValue(0);  
            setLabelStatus("");
        } else {
            setProgressao();
            setLabelStatus("Verificando senha...");
            if (!(ValidarSenha())) {
                JOptionPane.showMessageDialog(null, Mensagens.RetornaMensagem(9)); 
                jpfSenha.requestFocus(true);        
                jpfSenha.selectAll();
                jpbStatus.setValue(0);   
                setLabelStatus("");
            } else {
                jpbStatus.setValue(jpbStatus.getValue() + 1);
                TelaInicio telaInicio2 = new TelaInicio();
                telaInicio2.setTelaLogin(this);
                ArrayList<usuario> Lista = new ArrayList<usuario>();
                Lista.add(usuarioSistema.getUsuario());
                telaInicio2.setListaAcesso(Lista);
                telaInicio2.DefineAcesso();
                this.dispose();
                telaInicio2.setVisible(true);           
            }
        }
    }
}

private boolean ValidaCampoObrigatorio(boolean NovaSenha){
    boolean SemComponenteVazio = true;
    if (jtfLogin.getText().trim().equals("")) {
        DestacaComponente(jlbUsuario);
        SemComponenteVazio = false;
    } if (jpfSenha.getPassword().length == 0) {
        DestacaComponente(jlbSenha);
        SemComponenteVazio = false;
    } if (NovaSenha) {
        if (jpfNovaSenha.getPassword().length == 0) {
            DestacaComponente(jlbNovaSenha);
            SemComponenteVazio = false;
        }
    } if (!(SemComponenteVazio)) {
        JOptionPane.showMessageDialog(null, Mensagens.RetornaMensagem(1));        
    }
    return SemComponenteVazio;    
}

private void DestacaComponente(JLabel texto){
    texto.setForeground(Color.RED);
}

private void NormalizaComponente(JLabel texto){
    texto.setForeground(Color.black);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JButton jbtAlterar;
    private javax.swing.JButton jbtDesfazer;
    private javax.swing.JButton jbtEntrar;
    private javax.swing.JLabel jlbBoasVindas;
    private javax.swing.JLabel jlbNovaSenha;
    private javax.swing.JLabel jlbSenha;
    private javax.swing.JLabel jlbStatus;
    private javax.swing.JLabel jlbUsuario;
    private javax.swing.JProgressBar jpbStatus;
    private javax.swing.JPasswordField jpfNovaSenha;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtfLogin;
    // End of variables declaration//GEN-END:variables

}
