/*
 * TelaInicioVelho.java
 *
 * Created on 6 de Julho de 2008, 22:36
 */

package Telas;

import Telas.*;
import Telas.Formulario.ButtonTabComponent;
import Telas.Formulario.TelaAvaliacaoPedido;
import Telas.Formulario.TelaBanco;
import Telas.Formulario.TelaBotao;
import Telas.Formulario.TelaCadastroTela;
import Telas.Formulario.TelaCardapio;
import Telas.Formulario.TelaCargo;
import Telas.Formulario.TelaComposicaoCentesimal;
import Telas.Formulario.TelaContatoFornecedor;
import Telas.Formulario.TelaMovimentacao;
import Telas.Formulario.TelaFichaTecnica;
import Telas.Formulario.TelaFormaPagamento;
import Telas.Formulario.TelaFornecedor;
import Telas.Formulario.TelaFornecedorProduto;
import Telas.Formulario.TelaImportacao;
import Telas.Formulario.TelaMotivo;
import Telas.Formulario.TelaOrdemProducao;
import Telas.Formulario.TelaPagamentoFornecedor;
import Telas.Formulario.TelaPedido;
import Telas.Formulario.TelaPerfil;
import Telas.Formulario.TelaProduto;
import Telas.Formulario.TelaRefeicao;
import Telas.Formulario.TelaSaldoEstoque;
import Telas.Formulario.TelaUnidadeMedida;
import Telas.Formulario.TelaUsuario;


/**
 *
 * @author  Jonathan
 */
public class TelaInicioVelho extends javax.swing.JFrame {
    
    private TelaCargo telaCargo;
    private TelaUsuario telaUsuario;
    private TelaBotao telaBotao;
    private TelaCadastroTela telaCadastroTela;
    private TelaPerfil telaPerfil;
    //utilizados para efetuar o controle das abas
    public int ContAbas;
    public ButtonTabComponent btFecharAba;
    private TelaBanco telaBanco;
    private TelaFormaPagamento telaFormaPagamento;
    private TelaMotivo telaMotivo;
    private TelaUnidadeMedida telaUnidadeMedida;
    private TelaCardapio telaCardapio;
    private TelaFichaTecnica telaFichaTecnica;
    private TelaOrdemProducao telaOrdemProducao;
    private TelaProduto telaProduto;
    private TelaMovimentacao telaEstoque;
    private TelaSaldoEstoque telaSaldoEstoque;
    private TelaContatoFornecedor telaContatoFornecedor;
    private TelaFornecedor telaFornecedor;
    private TelaPagamentoFornecedor telaPagamentoFornecedor;
    private TelaFornecedorProduto telaFornecedorProduto;
    private TelaAvaliacaoPedido telaAvaliacaoPedido;
    private TelaPedido telaPedido;
    private TelaImportacao telaImportacao;
    private TelaComposicaoCentesimal telaComposicaoCentesimal;
    private TelaRefeicao telaRefeicao;

    /** Creates new form TelaInicioVelho */
    public TelaInicioVelho() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpTelas = new javax.swing.JDesktopPane();
        jtpTelas = new javax.swing.JTabbedPane();
        jmbMenus = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jiiBanco = new javax.swing.JMenuItem();
        jiiFormaPagamento = new javax.swing.JMenuItem();
        jiiMotivo = new javax.swing.JMenuItem();
        jiiUnidadeMedida = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jiiCardapio = new javax.swing.JMenuItem();
        jiiFichaTecnica = new javax.swing.JMenuItem();
        jiiOrdemProducao = new javax.swing.JMenuItem();
        jiiProduto = new javax.swing.JMenuItem();
        jiiComposicaoCentesimal = new javax.swing.JMenuItem();
        jmiRefeicao = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jiiEstoque = new javax.swing.JMenuItem();
        jiiSaldoEstoque = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jiiContatoFornecedor = new javax.swing.JMenuItem();
        jiiFornecedor = new javax.swing.JMenuItem();
        jiiPagamentoFornecedor = new javax.swing.JMenuItem();
        jiiProdutoFornecedor = new javax.swing.JMenuItem();
        jiiAvaliacaoPedido = new javax.swing.JMenuItem();
        jiiPedido = new javax.swing.JMenuItem();
        jiiImportacao = new javax.swing.JMenuItem();
        jmnSeguranca = new javax.swing.JMenu();
        jiiBotao = new javax.swing.JMenuItem();
        jiCargo = new javax.swing.JMenuItem();
        jiiPerfil = new javax.swing.JMenuItem();
        jiiTela = new javax.swing.JMenuItem();
        jiUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(null);

        jdpTelas.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jdpTelasComponentResized(evt);
            }
        });

        jtpTelas.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jtpTelas.setBounds(0, 0, 900, 450);
        jdpTelas.add(jtpTelas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jdpTelas, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Cadastro");

        jiiBanco.setText("Banco");
        jiiBanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jiiBancoMousePressed(evt);
            }
        });
        jMenu1.add(jiiBanco);

        jiiFormaPagamento.setText("Forma Pagamento");
        jiiFormaPagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jiiFormaPagamentoMousePressed(evt);
            }
        });
        jMenu1.add(jiiFormaPagamento);

        jiiMotivo.setText("Motivo");
        jiiMotivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jiiMotivoMousePressed(evt);
            }
        });
        jMenu1.add(jiiMotivo);

        jiiUnidadeMedida.setText("Unidade Medida");
        jiiUnidadeMedida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jiiUnidadeMedidaMousePressed(evt);
            }
        });
        jMenu1.add(jiiUnidadeMedida);

        jmbMenus.add(jMenu1);

        jMenu2.setText("Cardápio");

        jiiCardapio.setText("Cardápio");
        jiiCardapio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jiiCardapioMousePressed(evt);
            }
        });
        jMenu2.add(jiiCardapio);

        jiiFichaTecnica.setText("Ficha Técnica");
        jiiFichaTecnica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jiiFichaTecnicaMousePressed(evt);
            }
        });
        jMenu2.add(jiiFichaTecnica);

        jiiOrdemProducao.setText("Ordem de Produção");
        jiiOrdemProducao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jiiOrdemProducaoMousePressed(evt);
            }
        });
        jMenu2.add(jiiOrdemProducao);

        jiiProduto.setText("Produto");
        jiiProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jiiProdutoMousePressed(evt);
            }
        });
        jMenu2.add(jiiProduto);

        jiiComposicaoCentesimal.setText("Composição Centesimal");
        jiiComposicaoCentesimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jiiComposicaoCentesimalMousePressed(evt);
            }
        });
        jMenu2.add(jiiComposicaoCentesimal);

        jmiRefeicao.setText("Refeição");
        jmiRefeicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiRefeicaoMousePressed(evt);
            }
        });
        jMenu2.add(jmiRefeicao);

        jmbMenus.add(jMenu2);

        jMenu4.setText("Estoque");

        jiiEstoque.setText("Estoque");
        jiiEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jiiEstoqueMousePressed(evt);
            }
        });
        jMenu4.add(jiiEstoque);

        jiiSaldoEstoque.setText("Saldo do Estoque");
        jiiSaldoEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jiiSaldoEstoqueMousePressed(evt);
            }
        });
        jMenu4.add(jiiSaldoEstoque);

        jmbMenus.add(jMenu4);

        jMenu3.setText("Fornecedor");

        jiiContatoFornecedor.setText("Contato do Fornecedor");
        jiiContatoFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jiiContatoFornecedorMousePressed(evt);
            }
        });
        jMenu3.add(jiiContatoFornecedor);

        jiiFornecedor.setText("Fornecedor");
        jiiFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jiiFornecedorMousePressed(evt);
            }
        });
        jMenu3.add(jiiFornecedor);

        jiiPagamentoFornecedor.setText("Pagamento do Fornecedor");
        jiiPagamentoFornecedor.setName("jiiPagamentoFornecedor"); // NOI18N
        jiiPagamentoFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jiiPagamentoFornecedorMousePressed(evt);
            }
        });
        jMenu3.add(jiiPagamentoFornecedor);

        jiiProdutoFornecedor.setText("Produtos do Fornecedor");
        jiiProdutoFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jiiProdutoFornecedorMousePressed(evt);
            }
        });
        jMenu3.add(jiiProdutoFornecedor);

        jiiAvaliacaoPedido.setText("Avaliação do Pedido");
        jiiAvaliacaoPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jiiAvaliacaoPedidoMousePressed(evt);
            }
        });
        jMenu3.add(jiiAvaliacaoPedido);

        jiiPedido.setText("Pedido");
        jiiPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jiiPedidoMousePressed(evt);
            }
        });
        jMenu3.add(jiiPedido);

        jiiImportacao.setText("Importação");
        jiiImportacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jiiImportacaoMousePressed(evt);
            }
        });
        jMenu3.add(jiiImportacao);

        jmbMenus.add(jMenu3);

        jmnSeguranca.setText("Segurança");
        jmnSeguranca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmnSegurancaMousePressed(evt);
            }
        });

        jiiBotao.setText("Botão");
        jiiBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jiiBotaoMousePressed(evt);
            }
        });
        jmnSeguranca.add(jiiBotao);

        jiCargo.setText("Cargo");
        jiCargo.setName("jiiCargo"); // NOI18N
        jiCargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jiCargoMousePressed(evt);
            }
        });
        jmnSeguranca.add(jiCargo);

        jiiPerfil.setText("Perfil");
        jiiPerfil.setName("jiiPerfil"); // NOI18N
        jiiPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jiiPerfilMousePressed(evt);
            }
        });
        jmnSeguranca.add(jiiPerfil);

        jiiTela.setText("Tela");
        jiiTela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jiiTelaMousePressed(evt);
            }
        });
        jmnSeguranca.add(jiiTela);

        jiUsuario.setText("Usuario");
        jiUsuario.setName("jiiUsuario"); // NOI18N
        jiUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jiUsuarioMousePressed(evt);
            }
        });
        jmnSeguranca.add(jiUsuario);

        jmbMenus.add(jmnSeguranca);

        setJMenuBar(jmbMenus);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jiCargoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jiCargoMousePressed
    telaCargo = new TelaCargo();
    jtpTelas.add("Cargo", telaCargo);
    CarregarBotaoAba();
    
}//GEN-LAST:event_jiCargoMousePressed

public int getContAbas(int ContAbas){
    return ContAbas;
}

public void CarregarBotaoAba(){
    //btFecharAba = new ButtonTabComponent(jtpTelas,this);
    jtpTelas.setTabComponentAt(ContAbas, btFecharAba);						    
    ContAbas = ContAbas + 1;
    jtpTelas.setSelectedIndex(ContAbas - 1);    
}

private void jiUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jiUsuarioMousePressed
    telaUsuario = new TelaUsuario();
    telaUsuario.setDesktopPane(jdpTelas);
    jtpTelas.add("Usuário", telaUsuario);
    CarregarBotaoAba();
}//GEN-LAST:event_jiUsuarioMousePressed

private void jdpTelasComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jdpTelasComponentResized
    jtpTelas.setSize(jdpTelas.getSize());
}//GEN-LAST:event_jdpTelasComponentResized

private void jiiBotaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jiiBotaoMousePressed
    telaBotao = new TelaBotao();
    jtpTelas.add("Botão", telaBotao);
    CarregarBotaoAba();
}//GEN-LAST:event_jiiBotaoMousePressed

private void jiiTelaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jiiTelaMousePressed
    telaCadastroTela = new TelaCadastroTela();
    telaCadastroTela.setDesktopPane(jdpTelas);
    jtpTelas.add("Tela", telaCadastroTela);
    CarregarBotaoAba();
}//GEN-LAST:event_jiiTelaMousePressed

private void jmnSegurancaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmnSegurancaMousePressed

}//GEN-LAST:event_jmnSegurancaMousePressed

private void jiiPerfilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jiiPerfilMousePressed
    telaPerfil = new TelaPerfil();
    telaPerfil.setDesktopPane(jdpTelas);
    jtpTelas.add("Perfil", telaPerfil);
    CarregarBotaoAba();
}//GEN-LAST:event_jiiPerfilMousePressed

private void jiiBancoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jiiBancoMousePressed
    telaBanco = new TelaBanco();
    jtpTelas.add("Banco", telaBanco);
    CarregarBotaoAba();
}//GEN-LAST:event_jiiBancoMousePressed

private void jiiFormaPagamentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jiiFormaPagamentoMousePressed
    telaFormaPagamento = new TelaFormaPagamento();
    jtpTelas.add("Forma de Pagamento", telaFormaPagamento);
    CarregarBotaoAba();
}//GEN-LAST:event_jiiFormaPagamentoMousePressed

private void jiiMotivoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jiiMotivoMousePressed
    telaMotivo = new TelaMotivo();
    jtpTelas.add("Motivo", telaMotivo);
    CarregarBotaoAba();    
}//GEN-LAST:event_jiiMotivoMousePressed

private void jiiUnidadeMedidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jiiUnidadeMedidaMousePressed
    telaUnidadeMedida = new TelaUnidadeMedida();
    jtpTelas.add("Unidade de Medida", telaUnidadeMedida);
    CarregarBotaoAba(); 
}//GEN-LAST:event_jiiUnidadeMedidaMousePressed

private void jiiCardapioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jiiCardapioMousePressed
    telaCardapio = new TelaCardapio();
    telaCardapio.setDesktopPane(jdpTelas);
    jtpTelas.add("Cardápio", telaCardapio);
    CarregarBotaoAba(); 
}//GEN-LAST:event_jiiCardapioMousePressed

private void jiiFichaTecnicaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jiiFichaTecnicaMousePressed
    telaFichaTecnica = new TelaFichaTecnica();
    jtpTelas.add("Ficha Técnica", telaFichaTecnica);
    CarregarBotaoAba();    
}//GEN-LAST:event_jiiFichaTecnicaMousePressed

private void jiiOrdemProducaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jiiOrdemProducaoMousePressed
    telaOrdemProducao = new TelaOrdemProducao();
    jtpTelas.add("Ordem de Produção", telaOrdemProducao);
    CarregarBotaoAba();     
}//GEN-LAST:event_jiiOrdemProducaoMousePressed

private void jiiProdutoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jiiProdutoMousePressed
    telaProduto = new TelaProduto();
    telaProduto.setDesktopPane(jdpTelas);    
    jtpTelas.add("Produto", telaProduto);
    CarregarBotaoAba();    
}//GEN-LAST:event_jiiProdutoMousePressed

private void jiiEstoqueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jiiEstoqueMousePressed
    telaEstoque = new TelaMovimentacao();
    jtpTelas.add("Estoque", telaEstoque);
    CarregarBotaoAba();   
}//GEN-LAST:event_jiiEstoqueMousePressed

private void jiiSaldoEstoqueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jiiSaldoEstoqueMousePressed
    telaSaldoEstoque = new TelaSaldoEstoque();
    jtpTelas.add("Saldo do Estoque", telaSaldoEstoque);
    CarregarBotaoAba();   
}//GEN-LAST:event_jiiSaldoEstoqueMousePressed

private void jiiContatoFornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jiiContatoFornecedorMousePressed
    telaContatoFornecedor = new TelaContatoFornecedor();
    jtpTelas.add("Contato do Fornecedor", telaContatoFornecedor);
    CarregarBotaoAba();  
}//GEN-LAST:event_jiiContatoFornecedorMousePressed

private void jiiFornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jiiFornecedorMousePressed
    telaFornecedor = new TelaFornecedor();
    telaFornecedor.setDesktopPane(jdpTelas);
    jtpTelas.add("Fornecedor", telaFornecedor);
    CarregarBotaoAba(); 
}//GEN-LAST:event_jiiFornecedorMousePressed

private void jiiPagamentoFornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jiiPagamentoFornecedorMousePressed
    telaPagamentoFornecedor = new TelaPagamentoFornecedor();
    jtpTelas.add("Forma de Pagamento do Fornecedor", telaPagamentoFornecedor);
    CarregarBotaoAba(); 
}//GEN-LAST:event_jiiPagamentoFornecedorMousePressed

private void jiiProdutoFornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jiiProdutoFornecedorMousePressed
    telaFornecedorProduto = new TelaFornecedorProduto();
    jtpTelas.add("Fornecedor do Produto", telaFornecedorProduto);
    CarregarBotaoAba(); 
}//GEN-LAST:event_jiiProdutoFornecedorMousePressed

private void jiiAvaliacaoPedidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jiiAvaliacaoPedidoMousePressed
    telaAvaliacaoPedido = new TelaAvaliacaoPedido();
    jtpTelas.add("Avaliação do Pedido", telaAvaliacaoPedido);
    CarregarBotaoAba(); 
}//GEN-LAST:event_jiiAvaliacaoPedidoMousePressed

private void jiiPedidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jiiPedidoMousePressed
    telaPedido = new TelaPedido();
    telaPedido.setDesktopPane(jdpTelas);
    jtpTelas.add("Pedido", telaPedido);
    CarregarBotaoAba(); 
}//GEN-LAST:event_jiiPedidoMousePressed

private void jiiImportacaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jiiImportacaoMousePressed
    telaImportacao = new TelaImportacao();
    jtpTelas.add("Importação", telaImportacao);
    CarregarBotaoAba(); 
}//GEN-LAST:event_jiiImportacaoMousePressed

private void jiiComposicaoCentesimalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jiiComposicaoCentesimalMousePressed
    telaComposicaoCentesimal = new TelaComposicaoCentesimal();
    jtpTelas.add("Compoisção Centesimal", telaComposicaoCentesimal);
    CarregarBotaoAba(); 
}//GEN-LAST:event_jiiComposicaoCentesimalMousePressed

private void jmiRefeicaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiRefeicaoMousePressed
    telaRefeicao = new TelaRefeicao();
    jtpTelas.add("Refeição", telaRefeicao);
    CarregarBotaoAba();     
}//GEN-LAST:event_jmiRefeicaoMousePressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {

                TelaInicioVelho telaInicio = new TelaInicioVelho();
                telaInicio.setExtendedState(MAXIMIZED_BOTH);
                telaInicio.setVisible(true);
                
                
            }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JDesktopPane jdpTelas;
    private javax.swing.JMenuItem jiCargo;
    private javax.swing.JMenuItem jiUsuario;
    private javax.swing.JMenuItem jiiAvaliacaoPedido;
    private javax.swing.JMenuItem jiiBanco;
    private javax.swing.JMenuItem jiiBotao;
    private javax.swing.JMenuItem jiiCardapio;
    private javax.swing.JMenuItem jiiComposicaoCentesimal;
    private javax.swing.JMenuItem jiiContatoFornecedor;
    private javax.swing.JMenuItem jiiEstoque;
    private javax.swing.JMenuItem jiiFichaTecnica;
    private javax.swing.JMenuItem jiiFormaPagamento;
    private javax.swing.JMenuItem jiiFornecedor;
    private javax.swing.JMenuItem jiiImportacao;
    private javax.swing.JMenuItem jiiMotivo;
    private javax.swing.JMenuItem jiiOrdemProducao;
    private javax.swing.JMenuItem jiiPagamentoFornecedor;
    private javax.swing.JMenuItem jiiPedido;
    private javax.swing.JMenuItem jiiPerfil;
    private javax.swing.JMenuItem jiiProduto;
    private javax.swing.JMenuItem jiiProdutoFornecedor;
    private javax.swing.JMenuItem jiiSaldoEstoque;
    private javax.swing.JMenuItem jiiTela;
    private javax.swing.JMenuItem jiiUnidadeMedida;
    private javax.swing.JMenuBar jmbMenus;
    private javax.swing.JMenuItem jmiRefeicao;
    private javax.swing.JMenu jmnSeguranca;
    private javax.swing.JTabbedPane jtpTelas;
    // End of variables declaration//GEN-END:variables

}
