/*
 * TelaCargo8.java
 *
 * Created on 11 de Julho de 2008, 20:25
 */

package Telas.Formulario;

import Classes.Funcoes;
import Classes.cargo;
import Telas.Tabelas.JTableCargo;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import Classes.mensagens;
import Controller.ControllerCargo;
import javax.swing.JTextField;

/**
 *
 * @author  Jonathan
 */
public class TelaCargo extends TelaAncestral implements InterfacePadraoTela {
    
    private TelaUsuario telaUsuario;
    private ArrayList<cargo> ListaCargo;
    //usado para retorno de valor p outra tela
    private int id;
    private ControllerCargo Controller = new ControllerCargo();
    
    /** Creates new form BeanForm */
    public TelaCargo() {
        initComponents();  
    }
    

    @Override
    public void IniciarTela() {
        super.setTitulo("CARGO");
        Controller = new ControllerCargo();
        setPanelTela(this.jpnPesquisa, this.jpnCadastro, this.jpnTela);
        super.setComportamentoPanel(0);
        super.setComportamentoPanel(1);     
    }    
    
    public void SetTelaUsuario(TelaUsuario tlUsuario) {
        this.telaUsuario = tlUsuario;
    }
    
    
    
    @Override
    protected boolean ComportamentoExcluir() {
        if (Controller.EventoExcluir()) {
            JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(5));
            ComportamentoPesquisar();
            return true;
        } else {
            JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(6));
            return false;
        }
    }

    @Override
    protected boolean ComportamentoSalvar() { 
        boolean Gravou = false;
        if (super.VerificaCampos(jpnCadastro, 1)) {
            if (super.Operacao == 0) { 
                if (Controller.EventoSalvar(TelaParaController())) {
                    JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(2));
                    Gravou = true;
                } else
                    JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(3));
            } else if (super.Operacao == 1) {
                if (Controller.EventoAlterar(TelaParaController())) {
                    JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(4));
                    Gravou = true;
                } else
                    JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(3));                    
                }
            } else JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(1));
        return Gravou;
        }   
    @Override
    public ArrayList<Object> TelaParaController(){
        ArrayList<Object> Objeto = new ArrayList<Object>();
        Objeto.add(jtfDescricao.getText());
        return Objeto;
    }

    @Override
    public void ControllerParaTela(ArrayList<Object> Objeto){
        jtfDescricao.setText((String)Objeto.get(0));
    }
    @Override
    protected void ComportamentoNovo() {
        LimparFormulario(jpnCadastro); 
        super.setComportamentoPanel(2);
    }

    @Override
    protected boolean ComportamentoPesquisar() {
        ArrayList ListaParametros = null;
        boolean Achou = false;
        ListaParametros = setParametros();   
        ListaCargo = Controller.EventoPesquisar(ListaParametros);
        if (ListaCargo.isEmpty()) {
            JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(7));
        } else Achou = true;
        jtbCargo.setModel(new JTableCargo(ListaCargo));       
        return Achou;
    }
    
    public ArrayList<String> setParametros() {
        ArrayList<String> ListaParametros = new ArrayList<String>();
        if (!(jtfPesqDescricao.getText().trim().isEmpty())) {
            ListaParametros.add("Descricao");
            ListaParametros.add(jtfPesqDescricao.getText().toString());
        }
        return ListaParametros;            
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnTela = new javax.swing.JPanel();
        jpnPesquisa = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbCargo = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jlbDescricao1 = new javax.swing.JLabel();
        jtfPesqDescricao = new javax.swing.JTextField();
        jpnCadastro = new javax.swing.JPanel();
        jlb1Descricao = new javax.swing.JLabel();
        jtfDescricao = new javax.swing.JTextField();

        jpnTela.setLayout(new java.awt.BorderLayout());

        jpnPesquisa.setBackground(new java.awt.Color(243, 243, 243));
        jpnPesquisa.setLayout(new java.awt.BorderLayout());

        jtbCargo.setBackground(new java.awt.Color(243, 243, 243));
        jtbCargo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbCargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbCargoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbCargo);

        jpnPesquisa.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(243, 243, 243));

        jlbDescricao1.setText("Descrição");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jlbDescricao1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfPesqDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbDescricao1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfPesqDescricao, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jpnPesquisa.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jpnTela.add(jpnPesquisa, java.awt.BorderLayout.CENTER);

        jpnCadastro.setBackground(new java.awt.Color(243, 243, 243));
        jpnCadastro.setPreferredSize(new java.awt.Dimension(0, 100));

        jlb1Descricao.setText("* Descrição");
        jlb1Descricao.setName("jlb1Descricao"); // NOI18N

        jtfDescricao.setName("jtfDescricao"); // NOI18N

        javax.swing.GroupLayout jpnCadastroLayout = new javax.swing.GroupLayout(jpnCadastro);
        jpnCadastro.setLayout(jpnCadastroLayout);
        jpnCadastroLayout.setHorizontalGroup(
            jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlb1Descricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jpnCadastroLayout.setVerticalGroup(
            jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCadastroLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb1Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jpnTela.add(jpnCadastro, java.awt.BorderLayout.PAGE_START);

        getPanelAncestralCriado().add(jpnTela, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void jtbCargoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbCargoMouseClicked
if ((evt.getClickCount()==1) & (evt.getButton()== MouseEvent.BUTTON1)) {
        if (super.getTipoVisualizacao() == 0) {
            ControllerParaTela(Controller.EventoSelecionar(RetornaId(jtbCargo.getSelectedRow())));
            super.Operacao = 1;
            setComportamento(2);     
            super.setComportamentoPanel(2);
        } else {
            //super.jtfRetorno.setText(String.valueOf(RetornaId(jtbCargo.getSelectedRow())));  
            //this.telaUsuario.LerCargo(RetornaId(jtbCargo.getSelectedRow()));
            //this.telaUsuario.SetarCamposCargo();
            super.FechaFrameInterno();
          }
    }
}//GEN-LAST:event_jtbCargoMouseClicked


    @Override
    public int RetornaId(int Linha) {
        return ((cargo)ListaCargo.get(Linha)).getIdcargo();        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlb1Descricao;
    private javax.swing.JLabel jlbDescricao1;
    private javax.swing.JPanel jpnCadastro;
    private javax.swing.JPanel jpnPesquisa;
    private javax.swing.JPanel jpnTela;
    private javax.swing.JTable jtbCargo;
    private javax.swing.JTextField jtfDescricao;
    private javax.swing.JTextField jtfPesqDescricao;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setPanelTela(JPanel jpnPesquisa, JPanel jpnCadastro,JPanel jpnPrincipal) {
            setPanelFilha(jpnPesquisa, jpnCadastro, jpnPrincipal);
    }



}
