/*
 * TelaImportacao.java
 *
 * Created on 21 de Agosto de 2008, 20:34
 */

package Telas.Formulario;

import Classes.Funcoes;
import Classes.Importacao;
import Telas.Componentes.MensagensDefinidas;
import Telas.Componentes.TelaInterna;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JFileChooser;
import javax.swing.JPanel;

/**
 *
 * @author  Jonathan
 */
public class TelaImportacao extends javax.swing.JPanel {
    
    private TelaFornecedor telaFornecedor;
    private TelaInterna telaInterna;
    private JDesktopPane TelaPrincipal;
    private MensagensDefinidas mensagem;
    private Importacao importacao;
    private String idFornecedor;

    /** Creates new form TelaImportacao */
    public TelaImportacao() {
        initComponents();
        mensagem = new MensagensDefinidas();
        importacao = new Importacao();
    }
    
    public void setTelaPrincipal(JDesktopPane tela) {
        this.TelaPrincipal = tela;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaImportacao = new javax.swing.JTextArea();
        jtfFornecedor = new javax.swing.JTextField();
        jbtFornecedor = new javax.swing.JButton();
        jtfArquivo = new javax.swing.JTextField();
        jbtPedido1 = new javax.swing.JButton();
        edDescFornecedor = new javax.swing.JTextField();
        jbtImportar = new javax.swing.JButton();
        jlbTitulo = new javax.swing.JLabel();

        jLabel21.setText("Fornecedor");

        jLabel22.setText("Arquivo");

        jtaImportacao.setColumns(20);
        jtaImportacao.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jtaImportacao.setForeground(new java.awt.Color(0, 102, 255));
        jtaImportacao.setRows(5);
        jtaImportacao.setName("jtaImportacao"); // NOI18N
        jScrollPane1.setViewportView(jtaImportacao);

        jtfFornecedor.setName("jtfFornecedor"); // NOI18N

        jbtFornecedor.setText("jButton1");
        jbtFornecedor.setName("jbtFornecedor"); // NOI18N
        jbtFornecedor.setPreferredSize(new java.awt.Dimension(73, 19));
        jbtFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFornecedorActionPerformed(evt);
            }
        });

        jtfArquivo.setName("jtfArquivo"); // NOI18N

        jbtPedido1.setText("jButton1");
        jbtPedido1.setName("jbtPedido"); // NOI18N
        jbtPedido1.setPreferredSize(new java.awt.Dimension(73, 19));
        jbtPedido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPedido1ActionPerformed(evt);
            }
        });

        edDescFornecedor.setBackground(new java.awt.Color(204, 204, 204));
        edDescFornecedor.setEditable(false);
        edDescFornecedor.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        edDescFornecedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        edDescFornecedor.setName("edDescFornecedor"); // NOI18N

        jbtImportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/importar.png"))); // NOI18N
        jbtImportar.setText("Importar");
        jbtImportar.setToolTipText("Salvar as alterações feitas na tabela com os itens");
        jbtImportar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtImportar.setName("jbtImportar"); // NOI18N
        jbtImportar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtImportar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtImportarActionPerformed(evt);
            }
        });

        jlbTitulo.setBackground(new java.awt.Color(243, 243, 243));
        jlbTitulo.setFont(new java.awt.Font("Arial", 1, 14));
        jlbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTitulo.setText("Importação");
        jlbTitulo.setPreferredSize(new java.awt.Dimension(142, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1116, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edDescFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(427, Short.MAX_VALUE))
            .addComponent(jlbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 1116, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jbtImportar)
                .addContainerGap(1041, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jlbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtImportar)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(edDescFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jbtFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFornecedorActionPerformed
InstaciaTelaPedido();
}//GEN-LAST:event_jbtFornecedorActionPerformed

    private void InstaciaTelaPedido() {
        telaFornecedor = new TelaFornecedor();
        telaFornecedor.setTipoVisualizacao(1);
        telaFornecedor.setTelaImportacao(this);
        //super.TituloTela = "Produto";
        telaFornecedor.setDesktopPane(TelaPrincipal);
        CriarTelaInterna(telaFornecedor);
    }  
    
    public void setarCampos(String cod, String fornecedor, String id) {
        jtfFornecedor.setText(cod);
        idFornecedor = id;
        edDescFornecedor.setText(fornecedor);
    }
    
    public void CriarTelaInterna(Object Tela){
        EscreverMetodosAbstratosTelasInternas();
        CarregarTelaInterna(telaInterna, " Motivo ");                
        CarregarTela(Tela); 
    }
    
 private void EscreverMetodosAbstratosTelasInternas() {
        telaInterna = new TelaInterna(){

            @Override
            public void EventoFechar() {
                //HabilitaForm();               
            }

            @Override
            public void EventoAbrir() {
                //DesabilitaForm();
            }
        };
    }       
 
     protected void CarregarTelaInterna(TelaInterna interna, String titulo){
        interna.setTitle(titulo);
        interna.setResizable(true);
        interna.setClosable(true);
        interna.setMaximizable(false);
        interna.setIconifiable(false);
        interna.setSize(700,600);       
        interna.setLocation(Funcoes.CentralizarFrame(interna.getSize()));
        //return jifTela;
    }
     
    private void CarregarTela(Object Tela){
      ((JPanel)Tela).setVisible(true);
        //telaContatoFornecedor.setJTextRetorno(jtfTela);
        ((TelaAncestral)Tela).setFrameInterno(telaInterna);
        telaInterna.add(((JPanel)Tela));
        TelaPrincipal.add(telaInterna);
        telaInterna.setVisible(true);         
    }     
private void jbtPedido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPedido1ActionPerformed
   JFileChooser telaDiretorio = new JFileChooser();  
   int retorno = telaDiretorio.showOpenDialog(null);  
               if (retorno==JFileChooser.APPROVE_OPTION)  
                     jtfArquivo.setText(telaDiretorio.getSelectedFile().getAbsolutePath());  
}//GEN-LAST:event_jbtPedido1ActionPerformed

private void jbtImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtImportarActionPerformed
if ((jtfFornecedor.getText().trim().equals("")) || (jtfArquivo.getText().trim().equals(""))) {
        mensagem.ExibirMensagem(27);
    } else {
        importacao.setComponenteVisual(jtaImportacao);
        String problema = "";
            try {
                problema = importacao.ImportarPrecos(jtfArquivo.getText().trim(), idFornecedor);
                mensagem.ExibirMensagem(29);
            } catch (IOException ex) {
                mensagem.ExibirMensagem(28);
            }
        if (!problema.trim().equals("")) {
            mensagem.ExibirMensagemPersonalizada("Os produtos com os códigos : " + problema.substring(1) + 
                                                 " apresentaram problemas durante a atualização do preço.", 1);
        }
    }
}//GEN-LAST:event_jbtImportarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField edDescFornecedor;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtFornecedor;
    private javax.swing.JButton jbtImportar;
    private javax.swing.JButton jbtPedido1;
    private javax.swing.JLabel jlbTitulo;
    private javax.swing.JTextArea jtaImportacao;
    private javax.swing.JTextField jtfArquivo;
    private javax.swing.JTextField jtfFornecedor;
    // End of variables declaration//GEN-END:variables

}
