/*
 * TelaUnidadeMedida.java
 *
 * Created on 14 de Setembro de 2008, 06:05
 */

package Telas.Formulario;

import Controller.ControllerUnidadeMedida;
import Telas.Tabelas.JTableUnidadeMedida;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author  Jonathan
 */
public class TelaUnidadeMedida extends TelaAncestral implements InterfacePadraoTela{

    private List LIstaUnidade;
    private ControllerUnidadeMedida Controller;

    /** Creates new form BeanForm */
    public TelaUnidadeMedida() {
        initComponents();
        IniciarTela();
    }
    @Override
    public void IniciarTela() {
        setPanelTela(this.jpnPesquisa, this.jpnCadastro, this.jpnTela);
        super.setTitulo("Unidade de Medida");        
        super.setComportamentoPanel(0);
        super.setComportamentoPanel(1);
        LIstaUnidade = new ArrayList();
        Controller = new ControllerUnidadeMedida();
    }
   /*************************************************************************
     *     MÉTODOS SOBRESCRITO DA ANCESTRAL (EVENTOS DOS BOTÕES)
     ************************************************************************/ 
    @Override
    protected boolean ComportamentoExcluir() {
        boolean Excluiu = false;
        if (JOptionPane.showConfirmDialog(null, Controller.RetornaMensagem(11), "SICON", 0, 3, null) == 0) {       
            if (Controller.EventoExcluir()) {
                JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(5), "SICON", JOptionPane.ERROR_MESSAGE, new javax.swing.ImageIcon("C:\\Documents and Settings\\Jonathan\\workspace NetBeans\\TCC\\src\\Icones\\Selecionar.png"));     
                Excluiu = true;
                this.ComportamentoPesquisar();
            } else {
                JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(6), "SICON", JOptionPane.ERROR_MESSAGE, new javax.swing.ImageIcon("C:\\Documents and Settings\\Jonathan\\workspace NetBeans\\TCC\\src\\Icones\\delete.png"));
            }
        }
        return Excluiu;
    }

    @Override
    protected boolean ComportamentoSalvar() {
        boolean Gravou = false;
        if (super.VerificaCampos(jpnCadastro,1)) {
            if (super.Operacao == 0) {                                 
                if (Controller.EventoSalvar(TelaParaController())) {
                    JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(2), "SICON", JOptionPane.INFORMATION_MESSAGE, new javax.swing.ImageIcon("C:\\Documents and Settings\\Jonathan\\workspace NetBeans\\TCC\\src\\Icones\\Selecionar.png"));             
                    Gravou = true;
                } else
                    JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(3), "SICON", JOptionPane.ERROR_MESSAGE, new javax.swing.ImageIcon("C:\\Documents and Settings\\Jonathan\\workspace NetBeans\\TCC\\src\\Icones\\delete.png")); 
            } else if (super.Operacao == 1) {
                if (Controller.EventoAlterar(TelaParaController())) {
                    JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(4), "SICON", JOptionPane.INFORMATION_MESSAGE, new javax.swing.ImageIcon("C:\\Documents and Settings\\Jonathan\\workspace NetBeans\\TCC\\src\\Icones\\Selecionar.png")); 
                    Gravou = true;
                } else
                    JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(3), "SICON", JOptionPane.ERROR_MESSAGE, new javax.swing.ImageIcon("C:\\Documents and Settings\\Jonathan\\workspace NetBeans\\TCC\\src\\Icones\\delete.png"));                    
                }
            } else JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(1), "SICON", JOptionPane.ERROR_MESSAGE, new javax.swing.ImageIcon("C:\\Documents and Settings\\Jonathan\\workspace NetBeans\\TCC\\src\\Icones\\Pesquisar.png")); 
        return Gravou;
        }   

    @Override
    protected void ComportamentoNovo() {
        LimparFormulario(jpnCadastro);      
    }

    @Override
    protected boolean ComportamentoPesquisar() {
        boolean Achou = false;
        ArrayList ListaParametros = new ArrayList();
        ListaParametros = setParametros();
        LIstaUnidade = Controller.EventoPesquisar(ListaParametros);
        if (!(LIstaUnidade.isEmpty())){
            Achou = true;
        } else JOptionPane.showMessageDialog(null, Controller.RetornaMensagem(7), "SICON", JOptionPane.INFORMATION_MESSAGE, new javax.swing.ImageIcon("C:\\Documents and Settings\\Jonathan\\workspace NetBeans\\TCC\\src\\Icones\\Pesquisar.png"));             
        jtbUnidadeMedida.setModel(new JTableUnidadeMedida(LIstaUnidade)); 
        return Achou;
    }            

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jpnTela = new javax.swing.JPanel();
        jpnCadastro = new javax.swing.JPanel();
        jlb1Nome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jrbMiligrama = new javax.swing.JRadioButton();
        jrbGrama = new javax.swing.JRadioButton();
        jrbQuilograma = new javax.swing.JRadioButton();
        jpnPesquisa = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbUnidadeMedida = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jlb1Descricao1 = new javax.swing.JLabel();
        jtfNomePesq = new javax.swing.JTextField();

        jpnTela.setName("jpnTela"); // NOI18N
        jpnTela.setLayout(new java.awt.BorderLayout());

        jpnCadastro.setBackground(new java.awt.Color(243, 243, 243));
        jpnCadastro.setName("jpnCadastro"); // NOI18N

        jlb1Nome.setText("* Nome");
        jlb1Nome.setName("jlb1Nome"); // NOI18N

        jtfNome.setName("jtfNome"); // NOI18N

        jrbMiligrama.setBackground(new java.awt.Color(243, 243, 243));
        buttonGroup1.add(jrbMiligrama);
        jrbMiligrama.setText("Miligrama");
        jrbMiligrama.setName("jrbMiligrama"); // NOI18N

        jrbGrama.setBackground(new java.awt.Color(243, 243, 243));
        buttonGroup1.add(jrbGrama);
        jrbGrama.setText("Grama");
        jrbGrama.setName("jrbGrama"); // NOI18N

        jrbQuilograma.setBackground(new java.awt.Color(243, 243, 243));
        buttonGroup1.add(jrbQuilograma);
        jrbQuilograma.setText("Quilograma");
        jrbQuilograma.setName("jrbQuilograma"); // NOI18N

        javax.swing.GroupLayout jpnCadastroLayout = new javax.swing.GroupLayout(jpnCadastro);
        jpnCadastro.setLayout(jpnCadastroLayout);
        jpnCadastroLayout.setHorizontalGroup(
            jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCadastroLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jlb1Nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnCadastroLayout.createSequentialGroup()
                        .addComponent(jrbMiligrama)
                        .addGap(10, 10, 10)
                        .addComponent(jrbGrama)
                        .addGap(18, 18, 18)
                        .addComponent(jrbQuilograma)
                        .addGap(283, 283, 283))
                    .addGroup(jpnCadastroLayout.createSequentialGroup()
                        .addComponent(jtfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                        .addGap(88, 88, 88))))
        );
        jpnCadastroLayout.setVerticalGroup(
            jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCadastroLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb1Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbMiligrama)
                    .addComponent(jrbGrama)
                    .addComponent(jrbQuilograma))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jpnTela.add(jpnCadastro, java.awt.BorderLayout.CENTER);

        jpnPesquisa.setName("jpnPesquisa"); // NOI18N
        jpnPesquisa.setPreferredSize(new java.awt.Dimension(100, 170));
        jpnPesquisa.setLayout(new java.awt.BorderLayout());

        jtbUnidadeMedida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Unidade Medida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbUnidadeMedida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtbUnidadeMedidaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtbUnidadeMedida);

        jpnPesquisa.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(243, 243, 243));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 80));

        jlb1Descricao1.setText("Nome");
        jlb1Descricao1.setName("jlb1Descricao"); // NOI18N

        jtfNomePesq.setName("jtfDescricao"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jlb1Descricao1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNomePesq, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addGap(87, 87, 87))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb1Descricao1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNomePesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jpnPesquisa.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jpnTela.add(jpnPesquisa, java.awt.BorderLayout.PAGE_START);

        getPanelAncestralCriado().add(jpnTela, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void jtbUnidadeMedidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbUnidadeMedidaMousePressed
if ((evt.getClickCount()==1) & (evt.getButton()== MouseEvent.BUTTON1)) {
        if (super.getTipoVisualizacao() == 0) {
            ControllerParaTela(Controller.EventoSelecionar(RetornaId(jtbUnidadeMedida.getSelectedRow())));
            super.Operacao = 1;
            super.setLocalizacao(1);
            setComportamento(2);     
            super.setComportamentoPanel(2);
        } else {

        }
    }
}//GEN-LAST:event_jtbUnidadeMedidaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlb1Descricao1;
    private javax.swing.JLabel jlb1Nome;
    private javax.swing.JPanel jpnCadastro;
    private javax.swing.JPanel jpnPesquisa;
    private javax.swing.JPanel jpnTela;
    private javax.swing.JRadioButton jrbGrama;
    private javax.swing.JRadioButton jrbMiligrama;
    private javax.swing.JRadioButton jrbQuilograma;
    private javax.swing.JTable jtbUnidadeMedida;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNomePesq;
    // End of variables declaration//GEN-END:variables

   @Override
    public void setPanelTela(JPanel jpnPesquisa, JPanel jpnCadastro, JPanel jpnPrincipal) {
            setPanelFilha(jpnPesquisa, jpnCadastro, jpnPrincipal);
    }

    @Override
    public ArrayList<String> setParametros() {
        ArrayList ListaParametros = new ArrayList();        
        if (!(jtfNomePesq.getText().trim().equals(""))){
            ListaParametros.add("nome");
            ListaParametros.add(jtfNomePesq.getText());            
        } 
        return ListaParametros;
    }

    @Override
    public int RetornaId(int Linha) {
        return (Integer)((Object[])LIstaUnidade.get(Linha))[0];
    }

    @Override
    public ArrayList<Object> TelaParaController() {
        ArrayList Lista = new ArrayList();
        Lista.add(jtfNome.getText());        
        if (jrbMiligrama.isSelected()) {
            Lista.add(0);
        } else Lista.add(1);
        if (jrbGrama.isSelected()) {
            Lista.add(0);
        } else Lista.add(1);
        if (jrbQuilograma.isSelected()) {
            Lista.add(0);
        } else Lista.add(1);      
        return Lista;
    }

    @Override
    public void ControllerParaTela(ArrayList<Object> Objeto) {
        jtfNome.setText(Objeto.get(0).toString());
        if (Integer.parseInt(Objeto.get(1).toString()) == 0) {
            jrbMiligrama.setSelected(true);
        } else jrbGrama.setSelected(false);
        if (Integer.parseInt(Objeto.get(2).toString()) == 0) {
            jrbGrama.setSelected(true);
        } else jrbMiligrama.setSelected(false);
        if (Integer.parseInt(Objeto.get(3).toString()) == 0) {
            jrbQuilograma.setSelected(true);
        } else jrbQuilograma.setSelected(false);
    }

}
